### PR TITLE
Enhanced proximac command

### PR DESCRIPTION
**Pull request by vayn**
1. split command and argument parser
2. add option for daemon mode

### CODE REVIEW

**Comment by csujedihy** [comment]
Good Job! Appreciate your contribution!

**Comment by vayn** [comment]
@csujedihy Proximac is a great tool. I'm glad to contribute to this project :smiley:

**Comment by csujedihy** [comment]
Hey Vayn, is python3 necessary or any python3 feature is used in proximac.py? Some users complained that their systems prompted python3 interpreter is not found since the first line declares the python3 interpreter.

**Comment by vayn** [comment]
@csujedihy There is no need to claim Python 3 in shebang line actually. I've done to make the script  compatible with Python 2 and 3.

The Python 3 shebang is auto generated by my Vim editor. I have not  written Python 2 code for years :smile: 

You can just remove the first line, that's ok.

**Pull request merged**
